<?php

namespace AppBundle\Repository\API;

/**
 * ApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiRepository extends \Doctrine\ORM\EntityRepository
{
}
